### ISSUE TITLE
Unable able to audit page with error, Test run failed: unable to create driver.

### ISSUE THREAD

**Issue by mingfang** [Tanaguru/Tanaguru#124]
I unable to do my very first audit and am getting the error below in tanaguru.log.

```
16-09-2015 17:39:13:310 316993 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Launching audit Page on http://www.google.com
16-09-2015 17:39:13:798 317481 INFO  org.tanaguru.service.command.AbstractScenarioAuditCommandImpl  - Loading content for http://www.google.com
16-09-2015 17:39:38:315 341998 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Audit Duration has exceeded synchronous delay 25000
16-09-2015 17:39:59:826 363509 WARN  org.tanaguru.scenarioloader.ScenarioLoaderImpl  - Test run failed: unable to create driver.
16-09-2015 17:39:59:829 363512 ERROR org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - AUDIT CRASHED:org.tanaguru.entity.audit.AuditImpl@e318f59,http://www.google.com,1442425153
org.tanaguru.scenarioloader.exception.ScenarioLoaderException: java.lang.RuntimeException: Test run failed: unable to create driver.
	at org.tanaguru.scenarioloader.ScenarioLoaderImpl.run(ScenarioLoaderImpl.java:217)
	at org.tanaguru.service.ScenarioLoaderServiceImpl.loadScenario(ScenarioLoaderServiceImpl.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy100.loadScenario(Unknown Source)
	at org.tanaguru.service.command.AbstractScenarioAuditCommandImpl.loadContent(AbstractScenarioAuditCommandImpl.java:118)
	at org.tanaguru.service.AuditServiceThreadImpl.loadContent(AuditServiceThreadImpl.java:116)
	at org.tanaguru.service.AuditServiceThreadImpl.run(AuditServiceThreadImpl.java:96)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Test run failed: unable to create driver.
	at com.sebuilder.interpreter.TestRun.initRemoteWebDriver(TestRun.java:231)
	at org.tanaguru.sebuilder.interpreter.TgTestRun.initRemoteWebDriver(TgTestRun.java:373)
	at org.tanaguru.sebuilder.interpreter.TgTestRun.next(TgTestRun.java:181)
	at com.sebuilder.interpreter.TestRun.finish(TestRun.java:160)
	at com.sebuilder.interpreter.Script.run(Script.java:67)
	at org.tanaguru.scenarioloader.ScenarioLoaderImpl.run(ScenarioLoaderImpl.java:206)
	... 18 more
Caused by: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
ooglecode.com
1442425154884	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions/webdriver-staging
1442425154885	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1442425154885	addons.xpi	INFO	Mapping ubufox@ubuntu.com to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi
1442425154885	addons.xpi	DEBUG	checkForChanges
1442425154885	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.39.0","st":1442425154000,"mt":1442425154000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1442410961000,"mt":1440617365000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.1","st":1439278029000}}}
1442425154886	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1442425154887	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.39.0","st":1442425154000,"mt":1442425154000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1442410961000,"mt":1440617365000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.1","st":1439278029000}}}
1442425154887	addons.xpi	DEBUG	No changes found
1442425154890	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1442425154890	addons.manager	DEBUG	Provider finished startup: XPIProvider
1442425154890	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1442425154891	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1442425154891	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1442425154891	addons.manager	DEBUG	Starting provider: GMPProvider
1442425154893	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1442425154893	addons.manager	DEBUG	Provider finished startup: GMPProvider
1442425154893	addons.manager	DEBUG	Starting provider: PluginProvider
1442425154893	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1442425154894	addons.manager	DEBUG	Provider finished startup: PluginProvider
1442425154894	addons.manager	DEBUG	Completed startup sequence
1442425154910	addons.xpi-utils	DEBUG	Starting async load of XPI database /tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1442425154972	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1442425154972	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1442425154973	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1442425155014	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1442425155014	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1442425155015	addons.xpi-utils	DEBUG	Successfully read XPI database
1442425155053	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1442425155053	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1442425155054	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: https://self-repair.mozilla.org/en-US/repair/, line 7: ReferenceError: geoip_country_code is not defined
JavaScript error: https://self-repair.mozilla.org/en-US/repair/, line 7: ReferenceError: geoip_country_code is not defined

Build info: version: '2.39.0', revision: '14fa800511cc5d66d426e08b0b2ab926c7ed7398', time: '2013-12-16 13:18:38'
System info: host: 'b72f6a7e496e', ip: '10.244.160.23', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-63-generic', java.version: '1.8.0_60'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:130)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:250)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:110)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:195)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:190)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:186)
	at org.tanaguru.sebuilder.interpreter.webdriverfactory.FirefoxDriverFactory.make(FirefoxDriverFactory.java:67)
	at com.sebuilder.interpreter.TestRun.initRemoteWebDriver(TestRun.java:223)
	... 23 more
Caused by: org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
ooglecode.com
1442425154884	addons.xpi	DEBUG	Ignoring file entry whose name is not a valid add-on ID: /tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions/webdriver-staging
1442425154885	addons.xpi	INFO	Mapping {972ce4c6-7e08-4474-a285-3208198ce6fd} to /usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}
1442425154885	addons.xpi	INFO	Mapping ubufox@ubuntu.com to /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi
1442425154885	addons.xpi	DEBUG	checkForChanges
1442425154885	addons.xpi	DEBUG	Loaded add-on state from prefs: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.39.0","st":1442425154000,"mt":1442425154000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1442410961000,"mt":1440617365000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.1","st":1439278029000}}}
1442425154886	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
1442425154887	addons.xpi	DEBUG	getInstallState changed: false, state: {"app-profile":{"fxdriver@googlecode.com":{"d":"/tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions/fxdriver@googlecode.com","e":false,"v":"2.39.0","st":1442425154000,"mt":1442425154000}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}","e":true,"v":"40.0.3","st":1442410961000,"mt":1440617365000}},"app-system-share":{"ubufox@ubuntu.com":{"d":"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi","e":false,"v":"3.1","st":1439278029000}}}
1442425154887	addons.xpi	DEBUG	No changes found
1442425154890	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
1442425154890	addons.manager	DEBUG	Provider finished startup: XPIProvider
1442425154890	addons.manager	DEBUG	Starting provider: LightweightThemeManager
1442425154891	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
1442425154891	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
1442425154891	addons.manager	DEBUG	Starting provider: GMPProvider
1442425154893	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
1442425154893	addons.manager	DEBUG	Provider finished startup: GMPProvider
1442425154893	addons.manager	DEBUG	Starting provider: PluginProvider
1442425154893	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
1442425154894	addons.manager	DEBUG	Provider finished startup: PluginProvider
1442425154894	addons.manager	DEBUG	Completed startup sequence
1442425154910	addons.xpi-utils	DEBUG	Starting async load of XPI database /tomcat/temp/anonymous7483982091045408451webdriver-profile/extensions.json
*** Blocklist::_loadBlocklistFromFile: blocklist is disabled
1442425154972	addons.manager	DEBUG	Starting provider: <unnamed-provider>
1442425154972	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
1442425154973	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
1442425155014	addons.xpi-utils	DEBUG	Async JSON file read took 0 MS
1442425155014	addons.xpi-utils	DEBUG	Finished async read of XPI database, parsing...
1442425155015	addons.xpi-utils	DEBUG	Successfully read XPI database
1442425155053	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
1442425155053	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
1442425155054	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
JavaScript error: https://self-repair.mozilla.org/en-US/repair/, line 7: ReferenceError: geoip_country_code is not defined
JavaScript error: https://self-repair.mozilla.org/en-US/repair/, line 7: ReferenceError: geoip_country_code is not defined

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:118)
	... 30 more
16-09-2015 17:39:59:871 363554 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - krash email sent to [support@tanaguru.com] on audit n° 1
16-09-2015 17:39:59:893 363576 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - krash email sent to [admin@email.com] on audit n° 1
16-09-2015 17:39:59:947 363630 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Audit page terminated on http://www.google.com
```

**Comment by jkowalczyk** [comment]
Hi,

Regarding your log, it seems like tanaguru tries to use the firefox instance embedded by the system. 
As mentionned [prerequisites installation documentation](http://tanaguru.readthedocs.org/en/develop/prerequisites-webapp-doc/#firefox), an esr version of firefox is required to ensure the compatibility with the webdriver component.
The path of the binary has then to be set as a jvm option (-Dwebdriver.firefox.bin) in the /etc/default/tomcat7 file. 
This operation is normally done when the installation script is used.
Hope it fixes your problem.

Regards 

Jerome

**Comment by mingfang** [comment]
You are right @jkowalczyk.
After switching to firefox esr I finally was able to do a page audit.
If anyone is interest, I created a Dockerfile to run Tanaguru inside Docker.
https://github.com/mingfang/docker-tanaguru

**Comment by fhalna** [comment]
thanks @mingfang we  appreciate your contribution !
