### ISSUE TITLE
Jenkins job failing at Tanaguru runner step

### ISSUE THREAD

**Issue by Abubakar22** [Tanaguru/Tanaguru#160]
Hi All,

I am not able to integrate my Tanaguru with Jenkins, below is the Jenkins job error

Building remotely on tanaguru in workspace /opt/jenkins/workspace/Accesiblity_Test
Le chemin vers le contexte d'ex?cution est incorrect
Build step 'Tanaguru Runner' marked build as failure
Finished: FAILURE

My Tanaguru web is working fine but when i tried to run the below command I am getting this error

./bin/tanaguru.sh -d 99 -f /opt/firefox-31.4.0esr/firefox http://www.google.com

jenkins@devops-tanaguru-01:/opt/tanaguru$ ./bin/tanaguru.sh -d 99 -f /opt/firefox-31.4.0esr/firefox http://www.google.com
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Could not resolve placeholder 'persistenceXmlLocation' in string value [${persistenceXmlLocation}]
at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:209)
at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:220)
at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:84)
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:661)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.jav

Any help is appreciated

Thanks,
Mohammed

**Comment by rcharre** [comment]
Hello,
Can you check in your tanaguru.conf file (by default /etc/tanaguru/tanaguru.conf) the presence of the key : persistenceXmlLocation.

The default value for this key is : classpath:conf/tanaguru-persistence.xml
If this answer does not answer your issue, i will need the version of your Tanaguru environment.

Raphael Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
Hi Charre,
Sorry, I was busy last week and did not get a chance to follow up this issue

As you can see below in my system  **persistenceXmlLocation** key is **classpath:/conf/persistence.xml**
Do you want me to change it to default and recheck the issue?

![image](https://user-images.githubusercontent.com/17588727/57260269-75457600-7028-11e9-8826-e85d1d9c973a.png)

P.S My tanaguru web application is working fine and I can access it on browser but I am having issues with accessing Tanaguru CLI 


Regards,
Mohammed

**Comment by Abubakar22** [comment]
FYI My tanaguru version is 5.0.0

![image](https://user-images.githubusercontent.com/17588727/57328755-ded08d80-70d7-11e9-96b4-ebb51e00ce81.png)

**Comment by rcharre** [comment]
Hello Mohammed,

On your screenshot the key is "tgol-persistenceXmlLocation", corresponding to tanaguru online (web app). Can you please try to add (not replace) the following key and value to your conf file : 
persistenceXmlLocation=classpath:conf/tanaguru-persistence.xml

Regards,
Raphael Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
I have added persistenceXmlLocation=classpath:conf/tanaguru-persistence.xml and restarted my tomcat but still seeing the same issue

Regards,
Mohammed

**Comment by rcharre** [comment]
Sorry i didn't work on the CLI part yet.

After checking how this part works, i found that CLI use another tanaguru.conf file that you can find in the tanaguru folder you have extracted :
<tanaguru folder>/conf/context/tanaguru.conf

Can you check in this file the presence of the"persistenceXmlLocation" key ?

Regards,
Raphaël Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
Looks like we have some progress here, now I am getting below error. Can you please guide me

Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor#0' defined in class path resource [conf/context/beans-persistence.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: tanaguruPU] Unable to build Hibernate SessionFactory
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:527)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:733)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:454)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:140)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:84)
        at org.tanaguru.cli.Tanaguru.initServices(Tanaguru.java:362)
        at org.tanaguru.cli.Tanaguru.runAuditOnline(Tanaguru.java:224)
        at org.tanaguru.cli.Tanaguru.main(Tanaguru.java:190)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: tanaguruPU] Unable to build Hibernate SessionFactory
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1455)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:294)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:225)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:291)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:424)
        at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:277)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.<init>(PersistenceExceptionTranslationInterceptor.java:79)
        at org.springframework.dao.annotation.PersistenceExceptionTranslationAdvisor.<init>(PersistenceExceptionTranslationAdvisor.java:70)
        at org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor.setBeanFactory(PersistenceExceptionTranslationPostProcessor.java:103)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1475)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1443)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
        ... 12 more
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: tanaguruPU] Unable to build Hibernate SessionFactory
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1249)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.access$600(EntityManagerFactoryBuilderImpl.java:120)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:860)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:425)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:849)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:152)
        at org.hibernate.ejb.HibernatePersistence.createContainerEntityManagerFactory(HibernatePersistence.java:67)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:268)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:310)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1514)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1452)
        ... 27 more
Caused by: org.hibernate.AnnotationException: Use of @OneToMany or @ManyToMany targeting an unmapped class: org.tanaguru.entity.reference.TestImpl.accedwebSet[org.tanaguru.entity.reference.AccedewebImpl]
        at org.hibernate.cfg.annotations.CollectionBinder.bindManyToManySecondPass(CollectionBinder.java:1135)
        at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:794)
        at org.hibernate.cfg.annotations.CollectionBinder$1.secondPass(CollectionBinder.java:729)
        at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:70)
        at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1697)
        at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1426)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:857)
        ... 36 more

**Comment by rcharre** [comment]
Hello Mohammed,

It looks like we have some issues with the CLI for a long time.
If you are using an older referential than the RGAA2017 we can fix your probleme, otherwise I am sorry to announce you that need to fixe that and you won't be able to use it until the next release (That is coming very soon).

So if you use an older referential than the RGAA2017 this will do the job :
- go into your extracted tanaguru directory
- go into your lib folder
- extract tanaguru-resources-x-x-x.jar
- edit tanaguru-resources-x-x-x/conf/tanaguru-persistence.xml
- add the following line with the others "class" tags :
    <class>org.tanaguru.entity.reference.AccedewebImpl</class>
- delete  tanaguru-resources-x-x-x.jar
- create a jar from the folder you just edited : jar cvf tanaguru-resources-x-x-x.jar <path to the folder>/*
- move your jar into the lib folder

I hope this will help you.

Regards,
Raphaël Charre - Tanaguru Team

**Comment by trzepiz** [comment]
Hi, 
I have the same error with CLI in Tanaguru 5.3.0. And yes, this is RGAA2017  :/

`Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor#0' defined in class path resource [conf/context/beans-persistence.xml]: Initialization of bean failed; `

When we can expect a new version. Version 6 - I think?

**Comment by rcharre** [comment]
Hi,

Tanaguru 6.0.0 will be release very soon, I am actually updating our continous integration platform and correcting minor issues. We expect releasing the new version as soon as possible and i hope before mid June.

Regards,
Raphaël Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
Hi Raphaël Charre,

I can see Tanaguru 6 is out in the market, but looks like installation steps have been changed in new version and I cannot find install.sh anywhere.

Can you please guide us on how to install this new version of Tanaguru on my machine.

Thanks and Regards,
Mohammed

**Comment by rcharre** [comment]
Hi,

Indeed version 6 is out !
Due to bad refactoring of tanaguru modules, there were some missing files.
The issue should now be resolved.

The install steps of Tanaguru are the same as before, except that we now use newer version for java, tomcat and mysql.

If you do not want to completely reinstall Tanaguru there is an other way to proceed :
- copy <path>/install/web-app/tgol-web-app-6.0.0.war to you tomcat context folder
- use sql update scripts corresponding to your version that are stored in :
  - <path>/install/engine/sql-update
  - <path>/install/web-app/sql-update
- restart your tomcat
- update your firefox
And you are ready to go !

I'm sorry for this, and i thank you for your report.

**Comment by Abubakar22** [comment]
Hi Raphaël Charre,

Thank you for your support.

Now I am able to freshly install Tanaguru web application and also able to run a Scenario with sample Json file locally

But when I am trying to integrate with Jenkins, Jenkins job is failing without even starting execution with below error **Le chemin vers le contexte d'exécution est incorrect**

 I have also attached the screenshots 

![T_error1](https://user-images.githubusercontent.com/17588727/59885137-e5f9e500-937f-11e9-9ae9-68bce7cb7c35.JPG)
![T_error2](https://user-images.githubusercontent.com/17588727/59885150-ed20f300-937f-11e9-94dc-5b7632b43628.JPG)

**Comment by rcharre** [comment]
Hi,

Can you post the script that launch the Tanaguru executable file ?

Regards,
Raphaël Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
Hi Sorry for late reply, I was on vacation.

I am using Jenkins plugin  https://wiki.jenkins.io/display/JENKINS/Tanaguru+plugin which looks like have been updated recently 

Thanks and Regards,
Mohammed

**Comment by Abubakar22** [comment]
When I am trying to run a test locally with  command  **./bin/tanaguru.sh -f /opt/firefox/firefox-bin https://www.academy.com** I am getting below error 

crash (id+message): 29 javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Could not read entity state from ResultSet : EntityKey[org.tanaguru.entity.audit.AuditImpl#29]


for the same test in tanaguru log I am seeing below error

 ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper  - Cannot convert value '2019-07-11 19:56:44.000' from column 16 to TIMESTAMP.


Thanks and Regards,
Mohammed

**Comment by rcharre** [comment]
Hi,

Indeed the Tanaguru jenkins plugin has been updated recently (fixed some issues and added proxy management), I thought you wanted to use the CLI for a specific reason.

For you issue can you try to add : "?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf8mb4"
to your jdbc.url in tanaguru.conf (Don't forget that CLI does not use the same conf file than the web app)

Regards,
Raphaël Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
Hi Raphael,

Thanks for your overall support, 
I am able to launch the page audits manually from Tanaguru UI, but still I have below concerns 

- I am not able run Tanaguru tests through Jenkins, looks like there is an issue with Tanaguru plugin of Jenkins

- I am able to run audits for only website Pages and not able to run audits for whole site, Whenever I run audit for whole site it says **work in progress, an email will be sent once done**, waited for couple of weeks but no response and no report is generated in Tanaguru UI

It will really helpful if we can get the above fixed

Thanks and Regards,
Mohammed

**Comment by rcharre** [comment]
Hi,

I can see that official documentation needs an update for Jenkins plugin. To use it you will need activemq on you server ([5.10](https://archive.apache.org/dist/activemq/5.10.0/apache-activemq-5.10.0-bin.tar.gz) is a good version) you can download it here and extract it in /opt.

Then edit your /etc/tanaguru/tanaguru.conf file to add or edit those keys :
- brokerURL=tcp://localhost:61616?jms.prefetchPolicy.queuePrefetch=0
- auditQueueIn=toAuditQueue
- auditQueueOut=auditResultQueue

Next go to /var/lib/tomcat8/webapps/tanaguru/WEB-INF/lib/ and extract tgol-resources-6.0.1.jar
(unzip tgol-resources-6.0.1.jar -d tgol-resources-6.0.1)
Edit tgol-resources/conf/context/tgol-service.xml and uncomment "<import resource="classpath:conf/context/spring-jms-tanaguru.xml"/>"

Rezip the folder (zip -r tgol-resources tgol-resources-6.0.0.jar)

Start activemq (/opt/activemq/bin/activemq restart)

Restart tanaguru (service tomcat8 restart) And you should be ok.
------
For you second problem, it can be a RAM issue, to use last released versions you may need 6GB RAM to audit certain pages.

If this is not your issue i will need some stack trace to help you :)

Regards,

Raphaël Charre - Tanaguru Team

**Comment by Abubakar22** [comment]
Thanks Raphael, I am good with the new version of Tanaguru
