### ISSUE TITLE
Tanaguru 6.0 - tgol-service.xml - No such file or directory

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#161]
Hi. I install Tanaguru 6 on Ubuntu 18.04. All steps from https://tanaguru.readthedocs.io/en/develop/prerequisites-webapp-doc/ are done. 

**./install.sh** 

```
Directory creation:     .       .       OK
SQL inserts:            .       .       OK
grep: //etc/tanaguru/: Is a directory
Tanaguru config files creation: .         OK
sed: can't read WEB-INF/conf/tgol-service.xml: No such file or directory
```
**FAILURE : Unable to set up the tanaguru configuration**

**Comment by rcharre** [comment]
Hi,

Can you remove the following line from your install.sh file :

**Comment by rcharre** [comment]
Hi,
Can you remove this line from your install.sh file :

**Comment by trzepiz** [comment]
Hi. After remove this line: 

```
Directory creation:     .       .       OK
SQL inserts:            .       .       OK
grep: //etc/tanaguru/: Is a directory
Tanaguru config files creation: .         OK
replace META-INF/MANIFEST.MF? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
Tanaguru webapp creation:       .       OK
Firefox Profile Files creation:         .       OK
Tanaguru webapp configuration:  .       OK
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
Tanaguru admin creation:         .      OK
Adding JAVA_OPTS in tomcat configuration file
Tomcat configuration:   .       .       OK
```

**Well done, your Tanaguru is installed !**

Now when I started tanaguru in Tomcat Web Application Manager I have 

**FAIL - Application at context path [/tanaguru] could not be started**

root@vps:/var/log/tomcat8# cat catalina.out | grep Error

```
  at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) [xercesImpl-2.9.1.jar:na]
        at org.apache.xerces.util.ErrorHandlerWrapper.warning(Unknown Source) [xercesImpl-2.9.1.jar:na]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.9.1.jar:na]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.9.1.jar:na]
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) [xercesImpl-2.9.1.jar:na]
        at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source) [xercesImpl-2.9.1.jar:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat8-catalina-8.5.39.jar:8.5.39]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.dao.annotation.PersistenceExceptionTranslationPostProcessor#0' defined in class path resource [conf/context/tgol-beans-persistence.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/tgol-beans-persistence.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing column: Eaccess in tanaguru.TEST
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat8-catalina-8.5.39.jar:8.5.39]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/tgol-beans-persistence.xml]: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing column: Eaccess in tanaguru.TEST
```
I add ALTER TABLE `TEST` ADD `Eaccess` INT NULL DEFAULT NULL AFTER `Rank`;
And Tanaguru started in Tomcat Manager

I run my tanaguru in browser. Add user and contract. When I run audit I have 
**"Oups,Tanaguru is lost in space"**

root@vps:/var/log/tanaguru# cat tanaguru.log

```
18-06-2019 08:43:26:454 673146 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Launching audit Page on https://[adress_my_sites]
18-06-2019 08:43:30:160 676852 ERROR org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - AUDIT CRASHED:org.tanaguru.entity.audit.AuditImpl@69107727,https://[adress_my_sites],1560872606
java.lang.IllegalStateException: The driver executable does not exist: /opt/geckodriver
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
        at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:137)
        at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:132)
        at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:44)
        at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:167)
        at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
        at org.openqa.selenium.firefox.FirefoxDriver.toExecutor(FirefoxDriver.java:190)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at org.tanaguru.webdriver.driver.TanaguruDriver.<init>(TanaguruDriver.java:32)
        at org.tanaguru.webdriver.factory.TanaguruDriverFactory.createFirefoxTanaguruWebDriver(TanaguruDriverFactory.java:54)
        at org.tanaguru.scenarioloader.SeleneseLoaderImpl.initTanaguruDriver(SeleneseLoaderImpl.java:138)
        at org.tanaguru.scenarioloader.SeleneseLoaderImpl.run(SeleneseLoaderImpl.java:99)
        at org.tanaguru.service.ScenarioLoaderServiceImpl.loadUrlListContent(ScenarioLoaderServiceImpl.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
        at com.sun.proxy.$Proxy160.loadUrlListContent(Unknown Source)
        at org.tanaguru.service.command.PageAuditCommandImpl.loadContent(PageAuditCommandImpl.java:97)
        at org.tanaguru.service.AuditServiceThreadImpl.loadContent(AuditServiceThreadImpl.java:116)
        at org.tanaguru.service.AuditServiceThreadImpl.run(AuditServiceThreadImpl.java:96)
        at java.lang.Thread.run(Thread.java:748)
18-06-2019 08:43:30:710 677402 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - krash email sent to [support@tanaguru.com] on audit n° 2
18-06-2019 08:43:30:944 677636 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - krash email sent to [xxxxxxxxxxxxxxxxxxx] on audit n° 2
18-06-2019 08:43:31:057 677749 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Audit page terminated on https://[adress_my_sites]
18-06-2019 08:43:31:468 678160 ERROR org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - new KrashAuditException()
```

**Comment by rcharre** [comment]
Okay sorry about this, I just updated the doc : 
https://tanaguru.readthedocs.io/en/develop/prerequisites-webapp-doc/#geckodriver

I did in internal doc but not on this one. You can do this step without removing Tanaguru there is no probleme.

Regards,

Raphael Charre - Tanaguru Team

**Comment by trzepiz** [comment]
Hi
I replace my version geckodriver to yours and check audit. 
And still "Oups,Tanaguru is lost in space"

root@vps:/opt# cat /var/log/tanaguru/tanaguru.log | grep ERROR
```
org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 255
18-06-2019 09:05:26:479 1993171 ERROR org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - AUDIT CRASHED:org.tanaguru.entity.audit.AuditImpl@695cd5de,[MY SITE ADRESS],1560873923
18-06-2019 09:05:27:174 1993866 ERROR org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - new KrashAuditException()
```

**Comment by rcharre** [comment]
This error does not come from Tanaguru directly. After doing some research issue seems to came from firefox installation.

Did you download the version given in the doc (v61) and for the good architecture ?

Regards,

Raphael Charre - Tanaguru team

**Comment by trzepiz** [comment]
Yes. I have firefox from http://download-origin.cdn.mozilla.net/pub/firefox/releases/61.0/linux-x86_64/en-US/firefox-61.0.tar.bz2

But I think about xvfb. 
I start xvfb 
```
root@vps:/opt# /etc/init.d/xvfb start
root@vps:/opt# ps aux | grep xvfb
root     25965  0.0  0.0  14428  1012 pts/0    S+   09:37   0:00 grep --color=auto xvfb
root@vps:/opt#
```
xvfb not started ? 

I did everything as on docs site
https://tanaguru.readthedocs.io/en/develop/prerequisites-webapp-doc/#xvfb

**Comment by trzepiz** [comment]
I install firefox with apt (Firefox 61 is still in /opt/firefox)
```
apt-get update 
apt install firefox
```

Now audits started. I have another problem. When I click on details audit I have  Oups, Tanaguru is lost in space. i logs **Error 500** 

tail -f /var/log/tomcat8/localhost_access_log.2019-06-18.txt
```
[18/Jun/2019:10:18:11 -0700] "GET /tanaguru/dispatch.html HTTP/1.1" 302 -
[18/Jun/2019:10:18:11 -0700] "GET /tanaguru/home.html HTTP/1.1" 200 6982
[18/Jun/2019:10:18:15 -0700] "GET /tanaguru/home/contract.html?cr=2 HTTP/1.1" 200 7339
[18/Jun/2019:10:18:22 -0700] "GET /tanaguru/home/contract/audit-result.html?audit=9 HTTP/1.1" 302 -
[18/Jun/2019:10:18:26 -0700] "GET /tanaguru/home/contract/page-result.html?wr=9 HTTP/1.1" 500 2498
```

**Comment by rcharre** [comment]
Hi,

Do you have any ERROR log in your /var/log/tanaguru.log file during this audit ?
Or any log saying that the audit finished ?

If it is not the case can you check for running firefox instance.
And please can you tell me how much RAM is available on your server ?
Since the update and many changes in the way Tanaguru process website, it consumes more RAM than before.

Regards,

Raphael Charre - Tanaguru team

**Comment by trzepiz** [comment]
Hi. 

VPS - 2vCPU - 3072MB RAM - 30 GB SSD


root@vps:~# tail -f /var/log/tanaguru/tanaguru.log
```
19-06-2019 01:51:48:653 62375345 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Launching audit Page on [Adress_my_website]
19-06-2019 01:52:01:688 62388380 INFO  org.tanaguru.webdriver.driver.TanaguruDriver  - Successfully loaded page, firing new page : [Adress_my_website]
19-06-2019 01:52:11:664 62398356 INFO  org.tanaguru.webdriver.driver.TanaguruDriver  - colorExtractor executed
19-06-2019 01:52:11:965 62398657 INFO  org.tanaguru.webdriver.driver.TanaguruDriver  - Page doctype computed successfully
19-06-2019 01:52:13:795 62400487 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Audit Duration has exceeded synchronous delay 25000
19-06-2019 01:52:25:022 62411714 INFO  org.tanaguru.service.command.AuditCommandImpl  - Adapting [Adress_my_website]
19-06-2019 01:52:25:311 62412003 ERROR org.tanaguru.service.command.AuditCommandImpl  - Error reading stream exec java.io.IOException: Stream closed
19-06-2019 01:52:25:332 62412024 ERROR org.tanaguru.service.command.AuditCommandImpl  - Error reading stream exec java.io.IOException: Stream closed
19-06-2019 01:52:27:476 62414168 INFO  org.tanaguru.service.command.AuditCommandImpl  - [Adress_my_website] has been adapted
19-06-2019 01:52:27:553 62414245 INFO  org.tanaguru.service.command.AuditCommandImpl  - Processing [Adress_my_website]
19-06-2019 01:52:37:345 62424037 INFO  org.tanaguru.service.command.AuditCommandImpl  - [Adress_my_website] has been processed
19-06-2019 01:52:37:391 62424083 INFO  org.tanaguru.service.command.AuditCommandImpl  - Consolidating [Adress_my_website]
19-06-2019 01:52:41:850 62428542 INFO  org.tanaguru.service.command.AuditCommandImpl  - [Adress_my_website] has been consolidated
19-06-2019 01:52:41:866 62428558 INFO  org.tanaguru.service.command.AuditCommandImpl  - Analysing [Adress_my_website]
19-06-2019 01:52:41:882 62428574 ERROR org.tanaguru.analyser.AnalyserImpl  - ************************************
19-06-2019 01:52:41:883 62428575 ERROR org.tanaguru.analyser.AnalyserImpl  - error with w3cValidator json parser
19-06-2019 01:52:41:883 62428575 ERROR org.tanaguru.analyser.AnalyserImpl  - ************************************
19-06-2019 01:52:43:099 62429791 INFO  org.tanaguru.service.command.AuditCommandImpl  - [Adress_my_website] has been analysed
19-06-2019 01:52:43:147 62429839 INFO  org.tanaguru.service.command.AuditCommandImpl  - Cleaning-up data for [Adress_my_website]
19-06-2019 01:52:43:644 62430336 INFO  org.tanaguru.service.command.AuditCommandImpl  - Data cleaned-up for [Adress_my_website]
19-06-2019 01:52:43:792 62430484 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - success email sent to [michal@trzepizur.pl] on audit n° 11
19-06-2019 01:52:44:392 62431084 INFO  org.tanaguru.webapp.orchestrator.TanaguruOrchestratorImpl  - Audit page terminated on [Adress_my_website]
```

root@vps:~# cat /var/log/tomcat8/localhost_access_log.2019-06-19.txt
```
[MY_IP] - - [19/Jun/2019:01:54:48 -0700] "GET /tanaguru/home/contract/audit-result.html?audit=11 HTTP/1.1" 302 -
[MY_IP] - - [19/Jun/2019:01:54:51 -0700] "GET /tanaguru/home/contract/page-result.html?wr=11 HTTP/1.1" **500** 2493
```

root@vps:~# ps aux | grep firefox
```
root      1258  0.0  0.0  14428  1064 pts/1    S+   10:56   0:00 grep --color=auto firefox
tomcat8  24432  1.3 29.2 4754140 898228 ?      Sl   Jun18  14:34 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -Xms512M -Xmx2048M -DconfDir=file:///etc/tanaguru/ -DlogDir=/var/log/tanaguru -Dwebdriver.firefox.bin=/opt/firefox/firefox -Ddisplay=:99 -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat8 -Dcatalina.home=/usr/share/tomcat8 -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp org.apache.catalina.startup.Bootstrap start
tomcat8  25301  0.0  0.1  25420  4712 ?        Sl   Jun18   0:00 /opt/geckodriver --port=27010 -b /opt/firefox/firefox
tomcat8  26161  0.0  0.1  25420  4720 ?        Sl   Jun18   0:00 /opt/geckodriver --port=25202 -b /opt/firefox/firefox
tomcat8  26297  0.0  0.1  25420  4780 ?        Sl   Jun18   0:00 /opt/geckodriver --port=5222 -b /opt/firefox/firefox
```

**Comment by rcharre** [comment]
Hi,

Can you check in your database : 
- The presence of 'EACCESS' column in table 'TEST'
- If there are no duplicated value in column 'Cd_Evidence' in table 'Evidence'

I recommand you to kill those firefox process for non running audit, and if you can, to have 4GB+ RAM on your server. This is not de case here but it happens on huge website that the amount of RAM need is high, and if your server cannot supply Tanaguru lose the connection with firefox, this result in a crash and an useless firefox instance.

Regards,

Raphael Charre - Tanaguru team

**Comment by trzepiz** [comment]
Hi. 
This is my Evidence and TEST

Evidence
https://imgur.com/CzYeP9P
TEST
https://imgur.com/QBzJ7xT

I test small site (one page)

**Comment by rcharre** [comment]
Hi,

I just found out that you added Eaccess column to Test table (Will be fixed) but didn't update their value, that should have been done in install script, sorry for this.

There is a fix sql script that should fix the issue.
[fix.sql.zip](https://github.com/Tanaguru/Tanaguru/files/3306242/fix.sql.zip)

Regards,

Raphael Charre - Tanaguru team

**Comment by trzepiz** [comment]
Hi Raphael,
Yes. Now it's works !. I see detail page after audit.
