### ISSUE TITLE
Mass check accessibility 

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#180]
Is it possible to perform tests from a file (csv, xml or other)?. I would like to check over 100 different domain addresses.

I have a list of domains
1. domain.one
2. domain.two
e.t.c.

Maybe some cron jobs?
Have you any sugestion ?

**Comment by rcharre** [comment]
Hi,

This is a list of domain or subdomain ?
For subdomain "site audit" can do the job and crawl over all of them, if these are domains it won't.

It should be possible by using the command line interface.
The bad new is that you won't see the result on the webapp but in an output file.

After this you surely be able to create a cron job to audit all your domains.

Regards,

Raphaël CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
This is a list of domains. 

I have Web Application. How can I use CLI?

**Comment by rcharre** [comment]
Hi,

The CLI is in the package you downloaded to install Tanaguru.
You can find how to use it [here](https://tanaguru.readthedocs.io/en/develop/prerequisites-cli-doc/)

Regards,

Raphaël CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
Hi. 

Web Application work fine, but in CLI I have this error: 

( I copy /etc/tanaguru/tanaguru.conf to /opt/tanaguru-7.0.0-SNAPSHOT.i386/conf/context/tanaguru.conf )
 
root@ally:/opt/tanaguru-7.0.0-SNAPSHOT.i386# ./bin/tanaguru.sh https://google.com

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/tanaguru-7.0.0-SNAPSHOT.i386/lib/activemq-all-5.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/tanaguru-7.0.0-SNAPSHOT.i386/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/tanaguru-7.0.0-SNAPSHOT.i386/lib/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Could not resolve placeholder 'persistenceXmlLocation' in value "${persistenceXmlLocation}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'persistenceXmlLocation' in value "${persistenceXmlLocation}"
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:228)
        at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer.processProperties(PropertyPlaceholderConfigurer.java:213)
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:86)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85)
        at org.tanaguru.cli.Tanaguru.initServices(Tanaguru.java:362)
        at org.tanaguru.cli.Tanaguru.runAuditOnline(Tanaguru.java:224)
        at org.tanaguru.cli.Tanaguru.main(Tanaguru.java:190)
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'persistenceXmlLocation' in value "${persistenceXmlLocation}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:172)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:124)
        at org.springframework.beans.factory.config.PropertyPlaceholderConfigurer$PlaceholderResolvingStringValueResolver.resolveStringValue(PropertyPlaceholderConfigurer.java:232)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveStringValue(BeanDefinitionVisitor.java:296)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.resolveValue(BeanDefinitionVisitor.java:217)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitPropertyValues(BeanDefinitionVisitor.java:147)
        at org.springframework.beans.factory.config.BeanDefinitionVisitor.visitBeanDefinition(BeanDefinitionVisitor.java:85)
        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:225)
```

**Comment by rcharre** [comment]
Hi,

Can you check the presence of the key persistenceXmlLocation in your CLI conf file, you can find it in the folder of the CLI (not the one used by the webapp)

Regards,

Raphaël CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
Hi 

cat /opt/tanaguru-7.0.0-SNAPSHOT.i386/conf/context/tanaguru.conf | grep persistenceXmlLocation

tgol-persistenceXmlLocation=classpath:/conf/persistence.xml

**Comment by rcharre** [comment]
Hi,

I just read your first message again. I didn't see that you copied the configuration file. 
They are a bit different (on persistenceXmlLocation for exemple)

Regards,

Raphaël CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
Hi .. 
I edit oryginal conf file for CLI and try start tanaguru 

./bin/tanaguru.sh https://google.pl
but I have problem with:
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/myuser which is owned by myuser.)

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/tanaguru-7.0.0-SNAPSHOT.i386/lib/activemq-all-5.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/tanaguru-7.0.0-SNAPSHOT.i386/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/tanaguru-7.0.0-SNAPSHOT.i386/lib/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Thu Apr 09 11:13:09 UTC 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Thu Apr 09 11:13:09 UTC 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
1586430795188   geckodriver     INFO    geckodriver 0.21.0
1586430795191   geckodriver     INFO    Listening on 127.0.0.1:19424
1586430795344   mozrunner::runner       INFO    Running command: "/usr/lib/firefox/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.v3hVB5X205Yt"
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/myuser which is owned by myuser.)
org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 1
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'myhost', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-91-generic', java.version: '1.8.0_242'
Driver info: driver.version: TanaguruDriver
remote stacktrace:
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
        at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
        at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:122)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:125)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
        at org.tanaguru.webdriver.driver.TanaguruDriver.<init>(TanaguruDriver.java:32)
        at org.tanaguru.webdriver.factory.TanaguruDriverFactory.createFirefoxTanaguruWebDriver(TanaguruDriverFactory.java:54)
        at org.tanaguru.scenarioloader.SeleneseLoaderImpl.initTanaguruDriver(SeleneseLoaderImpl.java:138)
        at org.tanaguru.scenarioloader.SeleneseLoaderImpl.run(SeleneseLoaderImpl.java:99)
        at org.tanaguru.service.ScenarioLoaderServiceImpl.loadUrlListContent(ScenarioLoaderServiceImpl.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:55)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy144.loadUrlListContent(Unknown Source)
        at org.tanaguru.service.command.PageAuditCommandImpl.loadContent(PageAuditCommandImpl.java:99)
        at org.tanaguru.service.AuditServiceThreadImpl.loadContent(AuditServiceThreadImpl.java:116)
        at org.tanaguru.service.AuditServiceThreadImpl.run(AuditServiceThreadImpl.java:96)
        at java.lang.Thread.run(Thread.java:748)
crash (id+message): 26 org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 1
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:19:58.91Z'
System info: host: 'myhost', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-91-generic', java.version: '1.8.0_242'
Driver info: driver.version: TanaguruDriver
remote stacktrace:
```

**Comment by trzepiz** [comment]
I try start with a user 
 ./bin/tanaguru.sh https://google.pl

in my conf for CLI I have: 
crawlerHome=/home/trzepiz/tmp/
tempFolderRootPath=/home/trzepiz/tmp/



```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/trzepiz/tanaguru-7.0.0-SNAPSHOT.i386/lib/activemq-all-5.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/trzepiz/tanaguru-7.0.0-SNAPSHOT.i386/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/trzepiz/tanaguru-7.0.0-SNAPSHOT.i386/lib/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [conf/context/beans-persistence.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: tanaguruPU] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.CacheImplementor]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:142)
        at org.springframework.context.support.FileSystemXmlApplicationContext.<init>(FileSystemXmlApplicationContext.java:85)
        at org.tanaguru.cli.Tanaguru.initServices(Tanaguru.java:362)
        at org.tanaguru.cli.Tanaguru.runAuditOnline(Tanaguru.java:224)
        at org.tanaguru.cli.Tanaguru.main(Tanaguru.java:190)
Caused by: javax.persistence.PersistenceException: [PersistenceUnit: tanaguruPU] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.CacheImplementor]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:402)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1821)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1758)
        ... 14 more
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.cache.spi.CacheImplementor]
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:275)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.getService(SessionFactoryServiceRegistryImpl.java:98)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:238)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:462)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:938)
        at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:141)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
        ... 18 more
Caused by: net.sf.ehcache.CacheException: java.io.FileNotFoundException: /tmp/default-update-timestamps-region.data (Permission denied)
        at net.sf.ehcache.store.disk.DiskStorageFactory.<init>(DiskStorageFactory.java:146)
        at net.sf.ehcache.store.disk.DiskStore.create(DiskStore.java:154)
        at net.sf.ehcache.store.disk.DiskStore.createCacheStore(DiskStore.java:182)
        at net.sf.ehcache.Cache.initialise(Cache.java:1216)
        at net.sf.ehcache.CacheManager.initializeEhcache(CacheManager.java:1362)
        at net.sf.ehcache.CacheManager.addCacheNoCheck(CacheManager.java:1428)
        at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1304)
        at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1248)
        at org.hibernate.cache.ehcache.internal.EhcacheRegionFactory.createCache(EhcacheRegionFactory.java:159)
        at org.hibernate.cache.ehcache.internal.EhcacheRegionFactory.getOrCreateCache(EhcacheRegionFactory.java:147)
        at org.hibernate.cache.ehcache.internal.EhcacheRegionFactory.createTimestampsRegionStorageAccess(EhcacheRegionFactory.java:116)
        at org.hibernate.cache.spi.support.RegionFactoryTemplate.buildTimestampsRegion(RegionFactoryTemplate.java:70)
        at org.hibernate.cache.internal.EnabledCaching.<init>(EnabledCaching.java:80)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:33)
        at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:24)
        at org.hibernate.service.spi.SessionFactoryServiceInitiator.initiateService(SessionFactoryServiceInitiator.java:30)
        at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:62)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        ... 27 more
Caused by: java.io.FileNotFoundException: /tmp/default-update-timestamps-region.data (Permission denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
        at net.sf.ehcache.store.disk.DiskStorageFactory.allocateRandomAccessFiles(DiskStorageFactory.java:207)
        at net.sf.ehcache.store.disk.DiskStorageFactory.<init>(DiskStorageFactory.java:144)
        ... 44 more
```

**Comment by rcharre** [comment]
It seems that you current user does not have rights on file "/tmp/default-update-timestamps-region.data".
Give permissions or use an other that has them.

Regards,

Raphael CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
Hi.. 
Now working ok 

./bin/tanaguru.sh -o /home/trzepiz/output.txt https://google.com
**/home/trzepiz/output.txt is an invalid path for o option.**

How I can write all test from CLI to file ?

**Comment by rcharre** [comment]
Try to create the file before starting the audit.

Regards,
Raphael CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
Hi. 
I create file before starting audit. I always have 
`output.txt is an invalid path for o option.`

**Comment by trzepiz** [comment]
Ok .. I solved this. 

./bin/tanaguru.sh https://google.com >> file.txt
